// Generated by CIRCT firtool-1.62.1
package shelf.minitagepred

import chisel3._
import chisel3.experimental._

class MiniTagePred extends ExtModule {
  val clock = IO(Input(Clock()))
  val reset = IO(Input(UInt(1.W)))
  val io_in_pc = IO(Input(UInt(32.W)))
  val io_in_update_valid = IO(Input(UInt(1.W)))
  val io_in_update_bits_pcpn_tableIdx = IO(Input(UInt(3.W)))
  val io_in_update_bits_pcpn_entryIdx = IO(Input(UInt(5.W)))
  val io_in_update_bits_pcpn_entryTag = IO(Input(UInt(6.W)))
  val io_in_update_bits_bpu_pc = IO(Input(UInt(32.W)))
  val io_in_update_bits_bpu_isMissPredict = IO(Input(UInt(1.W)))
  val io_in_update_bits_bpu_actualTarget = IO(Input(UInt(32.W)))
  val io_in_update_bits_bpu_actualTaken = IO(Input(UInt(1.W)))
  val io_in_update_bits_bpu_btbType = IO(Input(UInt(2.W)))
  val io_in_pcpn_tableIdx = IO(Input(UInt(3.W)))
  val io_in_pcpn_entryIdx = IO(Input(UInt(5.W)))
  val io_in_pcpn_entryTag = IO(Input(UInt(6.W)))
  val io_out_pcpn_tableIdx = IO(Output(UInt(3.W)))
  val io_out_pcpn_entryIdx = IO(Output(UInt(5.W)))
  val io_out_pcpn_entryTag = IO(Output(UInt(6.W)))
  val io_out_pred = IO(Output(UInt(1.W)))
}
